# Generated by Django 5.2.6 on 2025-09-15 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_Bank_Management_System', '0002_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marked_as_Donated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_donated', models.DateField(auto_now_add=True)),
                ('marked_by', models.CharField(max_length=255)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_Bank_Management_System.donor')),
            ],
        ),
    ]
